[project]
name = "chemgraph"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ase>=3.26.0",
    "networkx>=3.5",
    "numpy>=2.3.5",
    "pytest>=9.0.1",
    "rdkit>=2025.9.1",
]
